### ISSUE TITLE
data in global.csv doesn't make sense

### ISSUE THREAD

**Issue by danielskatz** [popperized/swc-lesson#2]
for many of the years, global.csv shows values for types of fuels, but shows an integer 0 for per capita - it would be better to include global population for each year, and calculate a float value for per capita

**Comment by raynamharris** [comment]
Actually, global.csv has empty cells for per capita; however, scripts/get_mean_by_group.py says `# check for empty value (and assume zero if not found)`, and I think this should assume NA if not found instead of 0 if not found.
